### ISSUE TITLE
Error when running any command.

### ISSUE THREAD

**Issue by fernandezjose** [mixn/carbon-now-cli#22]
Hi,

I am getting the following error when I try to run any command, including `--help`

``` 
jfernand  ~   carbon-now --help
/Users/jfernand/.nvm/versions/node/v8.0.0/lib/node_modules/carbon-now-cli/cli.js:82
			...settings,
			^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

I am running MacOS High Sierra 10.13.6 and node/npm v8.0.0

**Comment by mixn** [comment]
Hi @fernandezjose, thanks for reaching out. :) 

You are correct in the sense that object spread is only available as of Node `v8.3` (I will clarify this in the docs soon).

I suggest upgrading or installing another version via [nvm](https://github.com/creationix/nvm). I just installed `8.0.0` and got the same error, but using (for example) `v8.11.3` or `v10.6.0` worked flawlessly.
