### ISSUE TITLE
Can't install carbon-now-cli 

### ISSUE THREAD

**Issue by neilrichter** [mixn/carbon-now-cli#33]
Her, I'm running MacOS latest version 10.13.6, and node 10.9, it throws the error : 
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/10.9.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'i',
1 verbose cli   '-g',
1 verbose cli   'carbon-now-cli' ]
2 info using npm@6.2.0
3 info using node@v10.9.0
4 verbose npm-session 11a4111ff23b4434
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/carbon-now-cli 16ms (from cache)
8 silly pacote tag manifest for carbon-now-cli@latest fetched in 27ms
9 timing stage:loadCurrentTree Completed in 179ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 2ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule carbon-now-cli@1.2.0 checking installable status
17 http fetch GET 200 https://registry.npmjs.org/file-exists 27ms (from cache)
18 http fetch GET 200 https://registry.npmjs.org/jsonfile 25ms (from cache)
19 http fetch GET 200 https://registry.npmjs.org/file-extension 29ms (from cache)
20 http fetch GET 200 https://registry.npmjs.org/listr 25ms (from cache)
21 http fetch GET 200 https://registry.npmjs.org/del 30ms (from cache)
22 http fetch GET 200 https://registry.npmjs.org/meow 26ms (from cache)
23 http fetch GET 200 https://registry.npmjs.org/globby 30ms (from cache)
24 http fetch GET 200 https://registry.npmjs.org/chalk 34ms (from cache)
25 silly pacote range manifest for file-exists@^5.0.1 fetched in 33ms
26 silly resolveWithNewModule file-exists@5.0.1 checking installable status
27 silly pacote range manifest for jsonfile@^4.0.0 fetched in 33ms
28 silly resolveWithNewModule jsonfile@4.0.0 checking installable status
29 silly pacote range manifest for file-extension@^4.0.5 fetched in 36ms
30 silly resolveWithNewModule file-extension@4.0.5 checking installable status
31 silly pacote range manifest for listr@^0.14.1 fetched in 33ms
32 silly resolveWithNewModule listr@0.14.2 checking installable status
33 silly pacote range manifest for del@^3.0.0 fetched in 39ms
34 silly resolveWithNewModule del@3.0.0 checking installable status
35 silly pacote range manifest for meow@^5.0.0 fetched in 34ms
36 silly resolveWithNewModule meow@5.0.0 checking installable status
37 silly pacote range manifest for globby@^8.0.1 fetched in 40ms
38 silly resolveWithNewModule globby@8.0.1 checking installable status
39 http fetch GET 200 https://registry.npmjs.org/lodash 38ms (from cache)
40 silly pacote range manifest for chalk@^2.4.1 fetched in 46ms
41 silly resolveWithNewModule chalk@2.4.1 checking installable status
42 http fetch GET 200 https://registry.npmjs.org/inquirer 46ms (from cache)
43 silly pacote range manifest for lodash@^4.17.10 fetched in 45ms
44 silly resolveWithNewModule lodash@4.17.11 checking installable status
45 http fetch GET 200 https://registry.npmjs.org/opn 13ms (from cache)
46 silly pacote range manifest for inquirer@^6.0.0 fetched in 51ms
47 silly resolveWithNewModule inquirer@6.2.0 checking installable status
48 http fetch GET 200 https://registry.npmjs.org/terminal-image 14ms (from cache)
49 http fetch GET 200 https://registry.npmjs.org/query-string 15ms (from cache)
50 http fetch GET 200 https://registry.npmjs.org/nanoid 18ms (from cache)
51 silly pacote range manifest for opn@^5.3.0 fetched in 18ms
52 silly resolveWithNewModule opn@5.4.0 checking installable status
53 silly pacote range manifest for terminal-image@^0.1.1 fetched in 16ms
54 silly resolveWithNewModule terminal-image@0.1.1 checking installable status
55 silly pacote range manifest for query-string@^6.1.0 fetched in 17ms
56 silly resolveWithNewModule query-string@6.1.0 checking installable status
57 silly pacote range manifest for nanoid@^1.1.0 fetched in 21ms
58 silly resolveWithNewModule nanoid@1.2.3 checking installable status
59 http fetch GET 200 https://registry.npmjs.org/puppeteer 19ms (from cache)
60 silly fetchPackageMetaData error for puppeteer@^1.5.0 Unexpected end of JSON input while parsing near '...er","version":"1.3.0-'
61 timing stage:rollbackFailedOptional Completed in 1ms
62 timing stage:runTopLevelLifecycles Completed in 258ms
63 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...er","version":"1.3.0-'
63 verbose stack     at JSON.parse (<anonymous>)
63 verbose stack     at parseJson (/usr/local/lib/node_modules/npm/node_modules/json-parse-better-errors/index.js:7:17)
63 verbose stack     at consumeBody.call.then.buffer (/usr/local/lib/node_modules/npm/node_modules/node-fetch-npm/src/body.js:96:50)
63 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
64 verbose cwd /Users/neilrichter
65 verbose Darwin 17.7.0
66 verbose argv "/usr/local/Cellar/node/10.9.0/bin/node" "/usr/local/bin/npm" "i" "-g" "carbon-now-cli"
67 verbose node v10.9.0
68 verbose npm  v6.2.0
69 error Unexpected end of JSON input while parsing near '...er","version":"1.3.0-'
70 verbose exit [ 1, true ]
```

**Comment by mixn** [comment]
@neilrichter Hi and thanks for reporting. :) Sorry for the delayed response, I’m in 🇨🇦 atm. 

Just like @wadie, I can’t reproduce your issue with the exact same setup. (`10.13.6` + `10.9`), sorry. Works without issues for me.

**Comment by neilrichter** [comment]
Works now, I guess it was cache. Thanks !
