### ISSUE TITLE
Can't not install it

### ISSUE THREAD

**Issue by horance-liu** [mixn/carbon-now-cli#49]
$ npm i -g carbon-now-cli
npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
/usr/local/bin/carbon-now -> /usr/local/lib/node_modules/carbon-now-cli/cli.js

> puppeteer@1.17.0 install /usr/local/lib/node_modules/carbon-now-cli/node_modules/puppeteer
> node install.js

ERROR: Failed to download Chromium r662092! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ Error: connect ETIMEDOUT 64.233.162.83:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
  -- ASYNC --
    at BrowserFetcher.<anonymous> (/usr/local/lib/node_modules/carbon-now-cli/node_modules/puppeteer/lib/helper.js:110:27)
    at Object.<anonymous> (/usr/local/lib/node_modules/carbon-now-cli/node_modules/puppeteer/install.js:64:16)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '64.233.162.83',
  port: 443 }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@1.17.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@1.17.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/horance/.npm/_logs/2019-06-01T02_21_43_394Z-debug.log

**Comment by mixn** [comment]
Please see [this](https://github.com/GoogleChrome/puppeteer/issues/2173) or [https://github.com/mixn/carbon-now-cli/issues/33](this) or [https://github.com/mixn/carbon-now-cli/issues/23](this). :)
