### ISSUE TITLE
Output Error. Sending code to carbon.now.sh

### ISSUE THREAD

**Issue by iamdevnitesh** [mixn/carbon-now-cli#67]
```
❯ carbon-now 1.go -i
? Syntax theme: Dracula
? Window theme: Black & White
? Font family: Iosevka
? Font size: 18px
? Background color: #ADB7C1
? Include window controls? Yes
? Include line numbers? No
? Auto adjust width? Yes
? Line height: 133%
? Vertical padding 0px
? Horizontal padding 0px
? Include drop shadow? No
? Make squared image? No
? Add Carbon watermark? No
? Export size 2x
? Export as… png
? Save these settings as a preset? No
  ✔ Processing 1.go
  ✔ Preparing connection
  ↓ Opening in browser [skipped]
  ✖ Fetching beautiful image
    → Execution context was destroyed, most likely because of a navigation.
    Copying image to clipboard

  Error: Sending code to https://carbon.now.sh went wrong.

  This is mostly due to:

  – Insensical input like `--start 10 --end 2`
  – Carbon being down or taking too long to respond
  – Your internet connection not working or being too slow

  Additional info:

  Error: Execution context was destroyed, most likely because of a navigation.
Error: Page crashed!
    at Page._onTargetCrashed (/usr/local/share/.config/yarn/global/node_modules/puppeteer/lib/Page.js:215:24)
    at CDPSession.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/puppeteer/lib/Page.js:123:56)
    at CDPSession.emit (node:events:394:28)
    at CDPSession._onMessage (/usr/local/share/.config/yarn/global/node_modules/puppeteer/lib/Connection.js:200:12)
    at Connection._onMessage (/usr/local/share/.config/yarn/global/node_modules/puppeteer/lib/Connection.js:112:17)
    at WebSocket.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/puppeteer/lib/WebSocketTransport.js:44:24)
    at WebSocket.onMessage (/usr/local/share/.config/yarn/global/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (node:events:394:28)
    at Receiver.receiverOnMessage (/usr/local/share/.config/yarn/global/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (node:events:394:28)
```

**Comment by BoKKeR** [comment]
I had the same problem, this solved it: https://github.com/mixn/carbon-now-cli/issues/64

**Comment by iamdevnitesh** [comment]
Thanks @BoKKeR . Closing the issue.
